---
system:
  hostname: SRX-1
  ntpserver: 1.1.1.1
  nameserver: 8.8.8.8
  domain: lab.com
  
services:
  - ssh
  - netconf ssh
  
management:
  interface: 'fxp0'
  unit: 0
  family: inet
  address: 192.168.200.200
  cidr: 24
